package services

import models.TBook
import models.TCatalog
import models.TTxBorrowDT
import models.TTxBorrowHD
import models.TUser
import models.common.CatalogListItem
import models.common.CatalogListItem
import models.common.UserListItem
import models.db.TDBBook
import models.db.TDBCatalog
import models.db.TDBTxBorrowDT
import models.db.TDBTxBorrowHD
import models.db.TDBUser
import models.common.STATUS_BOOK_AVL
import models.exception.BookNotFoundException
import models.exception.BookNotAvailableException
import models.TBook
import models.db.TDBBook
import models.TTxBorrowDT
import models.TTxBorrowHD
import models.db.TDBTxBorrowHD
import models.TUser
import models.TBook
import models.db.TDBUser
import models.db.TDBTxBorrowDT
import models.TCatalog
import models.OBTxBorrowHD
import models.db.TDBCatalog
import models.db.TDBBook
import models.TTxBorrowDT
import models.db.TDBTxBorrowHD
import models.TUser
import models.TBook
import models.db.TDBUser
import models.OBTxBorrowDT
import models.db.TDBTxBorrowDT
import models.TCatalog
import models.db.TDBCatalog
import models.db.TDBBook
import models.db.TDBTxBorrowHD
import models.TUser
import models.TBook
import models.db.TDBUser
import models.db.DBTxBorrowHD
import models.db.TDBTxBorrowDT
import models.TCatalog
import models.db.TDBCatalog
import models.db.TDBBook
import models.db.TDBTxBorrowHD
import models.TUser
import models.db.DBTxBorrowDT
import models.TBook
import models.db.TDBUser
import models.db.TDBTxBorrowDT
import models.TCatalog
import models.db.TDBCatalog
import models.db.TDBBook
import models.db.DBCatalog
import models.db.TDBTxBorrowHD
import models.TUser
import models.TBook
import models.db.TDBUser
import models.db.TDBTxBorrowDT
import models.TCatalog
import models.db.TDBCatalog
import models.db.TDBBook
import models.db.DBUser
import models.db.TDBTxBorrowHD
import models.TUser
import models.TBook
import models.db.TDBUser
import models.db.TDBTxBorrowDT
import models.TCatalog
import models.db.TDBCatalog
import models.db.TDBBook
import models.OBUser
import models.db.TDBTxBorrowHD
import models.TUser
import models.TBook
import models.db.TDBTxBorrowDT
import models.TCatalog
import models.db.TDBCatalog
import models.db.TDBBook
import models.db.DBBook
import models.db.TDBTxBorrowHD
import models.TBook
import models.db.TDBTxBorrowDT
import models.TCatalog
import models.db.TDBBook
import models.db.TDBTxBorrowHD
import models.TBook
import models.db.TDBTxBorrowDT
import models.TCatalog
import models.OBCatalog
import models.db.TDBBook
import models.db.TDBTxBorrowHD
import models.TBook
import models.OBBook
import models.db.TDBTxBorrowDT
import models.TCatalog

/**
 * This object serves as a bridge between the Business layer and Database layer.
 * Within this service object the user will process all the database request. 
 * All the results returned from this layer will already be in forms of 
 * Business Object instead of Database object.
 */
object CommonService extends TCommonService {}
