# Books schema

# --- !Ups

INSERT INTO BOOK (TITLE, AUTHOR, PUBLISHEDYEAR) VALUES ('ONE', 'SONE', 1901);
INSERT INTO BOOK (TITLE, AUTHOR, PUBLISHEDYEAR) VALUES ('TWO', 'STWO', 1902);
INSERT INTO BOOK (TITLE, AUTHOR, PUBLISHEDYEAR) VALUES ('THREE', 'STHREE', 1903);

# --- !Downs

DELETE FROM BOOK;
