DROP SEQUENCE COUNTRY_SEQNO_SEQ CASCADE;
DROP SEQUENCE USER_ROLE_SEQNO_SEQ CASCADE;
DROP SEQUENCE USERS_SEQNO_SEQ CASCADE;
DROP SEQUENCE CATALOG_SEQNO_SEQ CASCADE;
DROP SEQUENCE CATEGORY_SEQNO_SEQ CASCADE;
DROP SEQUENCE TX_BORROW_HD_SEQ CASCADE;

DROP TABLE NATIONALITY CASCADE;
DROP TABLE USER_ROLE CASCADE;
DROP TABLE USER_SECURITY;
DROP TABLE USERS CASCADE;
DROP TABLE CATALOG CASCADE;
DROP TABLE CATEGORY CASCADE;
DROP TABLE BOOK CASCADE;
DROP TABLE TX_BORROW_HD CASCADE;
DROP TABLE TX_BORROW_DT CASCADE;

CREATE SEQUENCE COUNTRY_SEQNO_SEQ;
CREATE SEQUENCE USER_ROLE_SEQNO_SEQ;
CREATE SEQUENCE USERS_SEQNO_SEQ;
CREATE SEQUENCE CATALOG_SEQNO_SEQ;
CREATE SEQUENCE CATEGORY_SEQNO_SEQ;
CREATE SEQUENCE TX_BORROW_HD_SEQ;

CREATE TABLE NATIONALITY (
	SEQNO INTEGER DEFAULT NEXTVAL('COUNTRY_SEQNO_SEQ'),
	NAME VARCHAR (50) NOT NULL,
	CREATE_USERCODE VARCHAR (15) NOT NULL,
	CREATE_TIMESTAMP TIMESTAMP NOT NULL,
	AUDIT_USERCODE VARCHAR (15) NOT NULL,
	AUDIT_TIMESTAMP TIMESTAMP NOT NULL,
	AUDIT_REASON VARCHAR (30),
	PRIMARY KEY (SEQNO)
 );

CREATE TABLE USER_ROLE (
	SEQNO INTEGER DEFAULT NEXTVAL('USER_ROLE_SEQNO_SEQ'), 
	NAME VARCHAR (20) NOT NULL,
	CREATE_USERCODE VARCHAR (15) NOT NULL,
	CREATE_TIMESTAMP TIMESTAMP NOT NULL,
	AUDIT_USERCODE VARCHAR (15) NOT NULL,
	AUDIT_TIMESTAMP TIMESTAMP NOT NULL,
	AUDIT_REASON VARCHAR (30),
	PRIMARY KEY (SEQNO)
 );

CREATE TABLE USERS (
	SEQNO INTEGER DEFAULT NEXTVAL('USERS_SEQNO_SEQ'),
	USERID VARCHAR (15) NOT NULL UNIQUE,
	NAME VARCHAR (100) NOT NULL,
	ADDRESS VARCHAR (100) NOT NULL,
	DOB DATE NOT NULL,
	GENDER BOOLEAN NOT NULL DEFAULT 'Y',
	ID_NUMBER VARCHAR (30) NOT NULL UNIQUE,
	NATIONALITY INTEGER NOT NULL,
	USER_ROLE_SEQNO INTEGER NOT NULL,
	IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE,
	CREATE_USERCODE VARCHAR (15) NOT NULL,
	CREATE_TIMESTAMP TIMESTAMP NOT NULL,
	AUDIT_USERCODE VARCHAR (15) NOT NULL,
	AUDIT_TIMESTAMP TIMESTAMP NOT NULL,
	AUDIT_REASON VARCHAR (30),
	PRIMARY KEY (SEQNO),
	FOREIGN KEY (USER_ROLE_SEQNO) REFERENCES USER_ROLE (SEQNO) MATCH FULL,
	FOREIGN KEY (NATIONALITY) REFERENCES NATIONALITY (SEQNO) MATCH FULL
 );

CREATE TABLE USER_SECURITY (
	USERID VARCHAR (15), 
	PASSWORD VARCHAR (80) NOT NULL,
	CREATE_USERCODE VARCHAR (15) NOT NULL,
	CREATE_TIMESTAMP TIMESTAMP NOT NULL,
	AUDIT_USERCODE VARCHAR (15) NOT NULL,
	AUDIT_TIMESTAMP TIMESTAMP NOT NULL,
	AUDIT_REASON VARCHAR (30),
	PRIMARY KEY (USERID),
	FOREIGN KEY (USERID) REFERENCES USERS(USERID)
 );

CREATE TABLE CATEGORY (
	SEQNO INTEGER DEFAULT NEXTVAL('CATEGORY_SEQNO_SEQ'),
	NAME VARCHAR (40) NOT NULL,
	CREATE_USERCODE VARCHAR (15) NOT NULL,
	CREATE_TIMESTAMP TIMESTAMP NOT NULL,
	AUDIT_USERCODE VARCHAR (15) NOT NULL,
	AUDIT_TIMESTAMP TIMESTAMP NOT NULL,
	AUDIT_REASON VARCHAR (30),
	PRIMARY KEY (SEQNO)
 );

CREATE TABLE CATALOG (
	SEQNO INTEGER DEFAULT NEXTVAL('CATALOG_SEQNO_SEQ'),
	CATEGORY_SEQNO INTEGER,
	TITLE VARCHAR (100),
	AUTHOR VARCHAR (50),
	PUBLISHED_YEAR INTEGER,
	ARRIVAL_DATE DATE,
	IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE,
	CREATE_USERCODE VARCHAR (15) NOT NULL,
	CREATE_TIMESTAMP TIMESTAMP NOT NULL,
	AUDIT_USERCODE VARCHAR (15) NOT NULL,
	AUDIT_TIMESTAMP TIMESTAMP NOT NULL,
	AUDIT_REASON VARCHAR (30),
	PRIMARY KEY (SEQNO),
	FOREIGN KEY (CATEGORY_SEQNO) REFERENCES CATEGORY (SEQNO) MATCH FULL
 );

CREATE TABLE BOOK (
	CATALOG_SEQNO INTEGER REFERENCES CATALOG(SEQNO),
	SEQNO INTEGER,
	REMARKS VARCHAR (300),
	STATUS VARCHAR (3) NOT NULL,
	STATUS_USERCODE VARCHAR (15) NOT NULL,
	STATUS_TIMESTAMP TIMESTAMP NOT NULL,
	IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE,
	ORIGIN VARCHAR (3) NOT NULL DEFAULT 'NEW',
	CREATE_USERCODE VARCHAR (15) NOT NULL,
	CREATE_TIMESTAMP TIMESTAMP NOT NULL,
	AUDIT_USERCODE VARCHAR (15) NOT NULL,
	AUDIT_TIMESTAMP TIMESTAMP NOT NULL,
	AUDIT_REASON VARCHAR (30),
	PRIMARY KEY (CATALOG_SEQNO, SEQNO)
 );

CREATE TABLE TX_BORROW_HD (
	SEQNO INTEGER DEFAULT nextval('TX_BORROW_HD_SEQ'),
	BORROWER_IDNUMBER VARCHAR (30) NOT NULL,
	BORROW_TIMESTAMP TIMESTAMP,
	OFFICER_USERID VARCHAR (15) NOT NULL,
	REMARKS VARCHAR (300),
	STATUS VARCHAR (3) NOT NULL,
	STATUS_USERCODE VARCHAR (15) NOT NULL,
	STATUS_TIMESTAMP TIMESTAMP NOT NULL,
	CREATE_USERCODE VARCHAR (15) NOT NULL,
	CREATE_TIMESTAMP TIMESTAMP NOT NULL,
	AUDIT_USERCODE VARCHAR (15) NOT NULL,
	AUDIT_TIMESTAMP TIMESTAMP NOT NULL,
	AUDIT_REASON VARCHAR (30),
	PRIMARY KEY (SEQNO)
 );

CREATE TABLE TX_BORROW_DT (
	HD_SEQNO INTEGER,
	CATALOG_SEQNO INTEGER NOT NULL,
	BOOK_SEQNO INTEGER NOT NULL,
	STATUS VARCHAR (3) NOT NULL,
	STATUS_USERCODE VARCHAR (15) NOT NULL,
	STATUS_TIMESTAMP TIMESTAMP NOT NULL,
	OFFICER_USERID VARCHAR (15) NOT NULL,
	CREATE_USERCODE VARCHAR (15) NOT NULL,
	CREATE_TIMESTAMP TIMESTAMP NOT NULL,
	AUDIT_USERCODE VARCHAR (15) NOT NULL,
	AUDIT_TIMESTAMP TIMESTAMP NOT NULL,
	AUDIT_REASON VARCHAR (30),
	PRIMARY KEY (HD_SEQNO, CATALOG_SEQNO, BOOK_SEQNO),
	FOREIGN KEY (HD_SEQNO)  REFERENCES TX_BORROW_HD(SEQNO) MATCH FULL,
	FOREIGN KEY (CATALOG_SEQNO, BOOK_SEQNO) REFERENCES BOOK(CATALOG_SEQNO, SEQNO) MATCH FULL
 );

