DELETE FROM USER_ROLE WHERE SEQNO IN (1,2);

INSERT INTO USER_ROLE (SEQNO, NAME,  CREATE_USERCODE, CREATE_TIMESTAMP, AUDIT_USERCODE, AUDIT_TIMESTAMP, AUDIT_REASON)
VALUES (1, 'ADMINISTRATOR', 'ADMIN', now(), 'ADMIN', now(), 'INITDB');

INSERT INTO USER_ROLE (SEQNO, NAME,  CREATE_USERCODE, CREATE_TIMESTAMP, AUDIT_USERCODE, AUDIT_TIMESTAMP, AUDIT_REASON)
VALUES (2, 'BORROWER', 'BORROWER', now(), 'ADMIN', now(), 'INITDB');

INSERT INTO USERS (USERID, NAME, ADDRESS, DOB, GENDER, ID_NUMBER, NATIONALITY, USER_ROLE_SEQNO, IS_DELETED, CREATE_USERCODE, CREATE_TIMESTAMP, AUDIT_USERCODE, AUDIT_TIMESTAMP, AUDIT_REASON)
VALUES ('ADMIN', 'ADMIN', 'ADMIN', now(), TRUE, 'ADMIN', 1, 1, FALSE, 'ADMIN', now(), 'ADMIN', now(), 'INITDB');

INSERT INTO USER_SECURITY (USERID, PASSWORD, CREATE_USERCODE, CREATE_TIMESTAMP, AUDIT_USERCODE, AUDIT_TIMESTAMP, AUDIT_REASON)
VALUES ('ADMIN', '[B@249a39df|fae50dfd4903e8e2faf931fc11784430f46418e2fd7f39d21ab6615b12262f19', 'ADMIN', now(), 'ADMIN', now(), 'INITDB');

